### ISSUE TITLE
Remove .stickOnScroll()

### ISSUE THREAD

**Issue by robizzt** [purtuga/jquery.stickOnScroll#8]
Hello,

I'm building responsive website. I use this plugin to stick the sidebar, but on mobile devices I don't want for sidebar to be sticked. So I made a resize function that should remove or unbind .stickOnScroll() function, but it dosen't work. This resize function works okey if you resize from mobile to desktop resolution (I just call .stickOnScroll() if window width is >= 1200px). But from desktop to mobile resolution, I dont know how to turn it off.

I don't know if this plugin has "disable" option, but if it dosen't maybe you could add it?

Any solutions?

Thank you.

**Comment by purtuga** [comment]
hi @robizzt 
The immediate solution I can think of would be to use the "new" (non-jquery based) version of this plugin ([here](https://github.com/purtuga/stick-on-scroll/blob/master/src/StickOnScroll.js)), but note that it is not quite ready for public consumption... not because it does work (it does... I'm using it in several projects), but because I have not published a built version nor have I had to a chance to publish usage documentation. 

The new version I mention above is built as a standalone class and includes additional methods that allow you to `.pause()` the stickyness as well as `.destroy()` the instance of the stick on scroll.  The api for it is very similar to the API of this jQuery based one:

```javascript
const stickInstance = StickOnScroll.create({
ele:                null,
    topOffset:          0,  // function supported as well
    bottomOffset:       5,  // function supported as well
    footerElement:      null,
    viewport:           WINDOW,
    stickClass:         'stickOnScroll-on',
    setParentOnStick:   false,
    setWidthOnStick:    false,  // Inserts a 0px div just before the sticky element
    onStick:            null,
    onUnStick:          null
})
```
The instance return is also an EventEmitter, so you would use the `.on()` method to listen for the `stick` and `un-stick` events. For your use case, you would need to call `stickInstance.pause()` when the window width is <1200px... and `stickInstance.resume()` when its `>=1200px`. 

Let me know if this helps. 

At the moment, I don't plan to update this plugin with additional features, mainly because I have the new version that removes jQuery dependency. BUT: I will entertain pull request :)

**Comment by robizzt** [comment]
Thank you on quick answer.

From now on I will use new version.

**Comment by purtuga** [comment]
Np. Your post has reminded me that I really need to finish up that new version and publish it to NPM. 
I'm closing this item out...
